import { resolve } from "path";
import { readFileSync, existsSync, writeFileSync } from "fs";

// ─── Load .env ───
function loadEnv(): Record<string, string> {
  const envPath = resolve(import.meta.dir, "../.env");
  const env: Record<string, string> = {};
  if (!existsSync(envPath)) {
    throw new Error(
      `.env not found at ${envPath}\nCreate one: cp .env.example .env\nThen set DISCORD_BOT_TOKEN`
    );
  }
  for (const line of readFileSync(envPath, "utf-8").split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq === -1) continue;
    env[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return env;
}

// ─── Types ───
export interface BotConfig {
  token: string;
  clientId: string;
  oauth2: {
    clientSecret: string;
    redirectUri: string;
  };
  guildId: string;
  roles: { unverified: string; verified: string; admin: string };
  channels: { welcome: string; rules: string; verification: string };
  backupChannels: string[];
  termsAndConditions: string;
  quiz: { maxAttempts: number; passPercentage: number; questions: QuizQuestion[] };
  rateLimits: { dmDelayMs: number; messagePostDelayMs: number };
}

export interface QuizQuestion {
  id: number;
  question: string;
  type: "yes_no" | "multiple_choice";
  options: string[];
  correctAnswer: string;
}

export interface ChannelMapping {
  sourceChannelId: string;
  targetChannelId: string;
  isForum?: boolean;
}

// ─── Config singleton ───
let _config: BotConfig | null = null;

export function loadConfig(): BotConfig {
  if (_config) return _config;

  const env = loadEnv();

  if (!env.DISCORD_BOT_TOKEN || env.DISCORD_BOT_TOKEN.startsWith("YOUR_")) {
    throw new Error("DISCORD_BOT_TOKEN not set in .env");
  }

  // Load JSON config (auto-generated by /setup)
  const configPath = resolve(import.meta.dir, "../config/bot.config.json");
  let json: any = {};
  if (existsSync(configPath)) {
    json = JSON.parse(readFileSync(configPath, "utf-8"));
  }

  _config = {
    token: env.DISCORD_BOT_TOKEN,
    clientId: json.clientId || "",
    oauth2: {
      clientSecret: env.OAUTH2_CLIENT_SECRET || json.oauth2?.clientSecret || "",
      redirectUri: env.OAUTH2_REDIRECT_URI || json.oauth2?.redirectUri || "",
    },
    guildId: env.GUILD_ID || json.guildId || "",
    roles: json.roles || { unverified: "", verified: "", admin: "" },
    channels: json.channels || { welcome: "", rules: "", verification: "" },
    backupChannels: json.backupChannels || [],
    termsAndConditions: json.termsAndConditions || "## Server Rules\n\n1. Be respectful.\n2. No spam.\n3. No NSFW.\n4. Follow Discord ToS.",
    quiz: json.quiz || { maxAttempts: 3, passPercentage: 80, questions: [] },
    rateLimits: json.rateLimits || { dmDelayMs: 1500, messagePostDelayMs: 1000 },
  };

  return _config;
}

export function saveConfig(config: Partial<BotConfig>): void {
  const configPath = resolve(import.meta.dir, "../config/bot.config.json");

  // Merge with existing
  let existing: any = {};
  if (existsSync(configPath)) {
    existing = JSON.parse(readFileSync(configPath, "utf-8"));
  }

  const merged = { ...existing, ...config };
  writeFileSync(configPath, JSON.stringify(merged, null, 2));
  _config = null; // Reset cache
}

export function saveGuildId(guildId: string): void {
  const envPath = resolve(import.meta.dir, "../.env");
  const env = loadEnv();
  env.GUILD_ID = guildId;
  const lines = Object.entries(env).map(([k, v]) => `${k}=${v}`);
  writeFileSync(envPath, lines.join("\n"));
}

export function getConfig(): BotConfig {
  return loadConfig();
}

// ─── Channel Mappings (for restore module) ───
const MAPPINGS_PATH = resolve(import.meta.dir, "../config/channel-mappings.json");

export function loadChannelMappings(): ChannelMapping[] {
  if (!existsSync(MAPPINGS_PATH)) return [];
  const data = JSON.parse(readFileSync(MAPPINGS_PATH, "utf-8"));
  const mappings: ChannelMapping[] = [];
  if (data.mappings) {
    for (const [source, target] of Object.entries(data.mappings)) {
      mappings.push({ sourceChannelId: source, targetChannelId: target as string, isForum: false });
    }
  }
  if (data.forumMappings) {
    for (const [source, target] of Object.entries(data.forumMappings)) {
      mappings.push({ sourceChannelId: source, targetChannelId: target as string, isForum: true });
    }
  }
  return mappings;
}

export function saveChannelMappings(mappings: ChannelMapping[]): void {
  const regular: Record<string, string> = {};
  const forum: Record<string, string> = {};
  for (const m of mappings) {
    if (m.isForum) forum[m.sourceChannelId] = m.targetChannelId;
    else regular[m.sourceChannelId] = m.targetChannelId;
  }
  writeFileSync(MAPPINGS_PATH, JSON.stringify({ mappings: regular, forumMappings: forum }, null, 2));
}
